In [1]:
import numpy as np

In [3]:
#define numpy array
mylist = [1,2,3]
#converting list to numpy array
mynparray = np.array(mylist)
print(mynparray)
print(mynparray.shape)

[1 2 3]
(3,)


In [9]:
mylist = [[1,2,3],[44,52,78]]
mynparray = np.array(mylist)
print(mynparray)
print(mynparray.shape)
print("The first row is : %s" %mynparray[0])
print("The last row is : %s" %mynparray[-1])
print("Specific element : %s" %mynparray[1,1])
print("Specific column : %s" %mynparray[:,2])

[[ 1  2  3]
 [44 52 78]]
(2, 3)
The first row is : [1 2 3]
The last row is : [44 52 78]
Specific element : 52
Specific column : [ 3 78]


In [10]:
a = np.array([2,2,2])
b = np.array([3,3,3])
print("sum : %s" %(a+b))
print("product : %s" %(a*b))

sum : [5 5 5]
product : [6 6 6]
